# JEKYLL SITE CONFIGURATION FILE
title: Thomas Varnish
description: >- # this means to ignore newlines until "baseurl:" 
  Aspiring physicist. Space enthusiast. Occasional maker of things. 
  Studying MSci Physics at Imperial College London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thomasvarnish.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

author:
  twitter: ThomasVarnish
  github:  tvarnish
  linkedin: thomasvarnish
  orcid: 0000-0002-8078-214X
  email: 
    user: hsinravt
    domain: tim
    tld: ude.

sitepages:
  - url: 
    label: Home
  # - url: research/
  #   label: Research
    # - url: blog/
  #   label: Blog
  - url: cv/
    label: CV

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
kramdown:
  footnote_backlink: "&#x2934;&#xFE0E;&nbsp;&nbsp;"