# JEKYLL SITE CONFIGURATION FILE
title: Thomas Varnish
description: >- # this means to ignore newlines until "baseurl:" 
  Aspiring physicist. Space enthusiast. Occasional maker of things. 
  Studying MSci Physics at Imperial College London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thomasvarnish.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

author:
  twitter: ThomasVarnish
  github:  tvarnish
  linkedin: thomasvarnish
  email: 
    user: 71vwt
    domain: lairepmi
    tld: ku.ca.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed